### ISSUE TITLE
Mingw targets

### ISSUE THREAD

**Issue by joshfinley** [joshfinley/pecpp#14]

**Comment by LordRibblesdale** [comment]
I would like to work on this issue, if possible :)

**Comment by joshfinley** [comment]
Thanks for your contribution - I merged https://github.com/joshfinley/pecpp/commit/c2833bbcee2e27139616be4247e86c1cde74ab03 which adds Windows Mingw support. If you are interested, I would like to add Linux Mingw support as well.

**Comment by LordRibblesdale** [comment]
I'll try to create an environment on a virtual machine (meanwhile if someone has already a prepared envionment, feel free to prepare a PR for Hacktoberfest ;) )

**Comment by LordRibblesdale** [comment]
I've set #20 PR for Linux MinGW support (with a little note inside). Tell me what you think about ;)

**Comment by joshfinley** [comment]
Added in https://github.com/joshfinley/pecpp/pull/20. Many thanks @LordRibblesdale!
